// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SofkaUPrueba.Infrastructure.Persistence;

#nullable disable

namespace SofkaUPrueba.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = "1",
                            Name = "FACIL"
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = "2",
                            Name = "INTERMEDIO"
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = "3",
                            Name = "MEDIO"
                        },
                        new
                        {
                            Id = 4,
                            Difficulty = "4",
                            Name = "PROFESIONAL"
                        },
                        new
                        {
                            Id = 5,
                            Difficulty = "5",
                            Name = "EXPERTO"
                        });
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.OptionsQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Iscorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionsId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Iscorrect = true,
                            Name = "mamífero",
                            QuestionsId = 1
                        },
                        new
                        {
                            Id = 2,
                            Iscorrect = false,
                            Name = "anfibios",
                            QuestionsId = 1
                        },
                        new
                        {
                            Id = 3,
                            Iscorrect = false,
                            Name = "reptiles",
                            QuestionsId = 1
                        },
                        new
                        {
                            Id = 4,
                            Iscorrect = false,
                            Name = "cefalópodos",
                            QuestionsId = 1
                        },
                        new
                        {
                            Id = 5,
                            Iscorrect = false,
                            Name = "300",
                            QuestionsId = 2
                        },
                        new
                        {
                            Id = 6,
                            Iscorrect = false,
                            Name = "150",
                            QuestionsId = 2
                        },
                        new
                        {
                            Id = 7,
                            Iscorrect = false,
                            Name = "200",
                            QuestionsId = 2
                        },
                        new
                        {
                            Id = 8,
                            Iscorrect = true,
                            Name = "206",
                            QuestionsId = 2
                        },
                        new
                        {
                            Id = 9,
                            Iscorrect = false,
                            Name = "ácido, salado, frutoso, verdura y tierroso",
                            QuestionsId = 3
                        },
                        new
                        {
                            Id = 10,
                            Iscorrect = true,
                            Name = "dulce, amargo, ácido, salado y umami",
                            QuestionsId = 3
                        },
                        new
                        {
                            Id = 11,
                            Iscorrect = false,
                            Name = "venenoso, frutoso, dulce, baboso y umami",
                            QuestionsId = 3
                        },
                        new
                        {
                            Id = 12,
                            Iscorrect = false,
                            Name = "amargo, salado, aceitoso, tierroso y empalagoso",
                            QuestionsId = 3
                        },
                        new
                        {
                            Id = 13,
                            Iscorrect = false,
                            Name = "España",
                            QuestionsId = 4
                        },
                        new
                        {
                            Id = 14,
                            Iscorrect = false,
                            Name = "Canada",
                            QuestionsId = 4
                        },
                        new
                        {
                            Id = 15,
                            Iscorrect = true,
                            Name = "antártida",
                            QuestionsId = 4
                        },
                        new
                        {
                            Id = 16,
                            Iscorrect = false,
                            Name = "Rusia",
                            QuestionsId = 4
                        },
                        new
                        {
                            Id = 17,
                            Iscorrect = false,
                            Name = "Diana",
                            QuestionsId = 5
                        },
                        new
                        {
                            Id = 18,
                            Iscorrect = false,
                            Name = "Maria isabel V",
                            QuestionsId = 5
                        },
                        new
                        {
                            Id = 19,
                            Iscorrect = false,
                            Name = "Tereza de calcuta",
                            QuestionsId = 5
                        },
                        new
                        {
                            Id = 20,
                            Iscorrect = true,
                            Name = "Isabel II",
                            QuestionsId = 5
                        },
                        new
                        {
                            Id = 21,
                            Iscorrect = false,
                            Name = "Mongolia",
                            QuestionsId = 6
                        },
                        new
                        {
                            Id = 22,
                            Iscorrect = false,
                            Name = "Roma",
                            QuestionsId = 6
                        },
                        new
                        {
                            Id = 23,
                            Iscorrect = true,
                            Name = "Grecia",
                            QuestionsId = 6
                        },
                        new
                        {
                            Id = 24,
                            Iscorrect = false,
                            Name = "Italia",
                            QuestionsId = 6
                        },
                        new
                        {
                            Id = 25,
                            Iscorrect = false,
                            Name = "1920",
                            QuestionsId = 7
                        },
                        new
                        {
                            Id = 26,
                            Iscorrect = true,
                            Name = "1945",
                            QuestionsId = 7
                        },
                        new
                        {
                            Id = 27,
                            Iscorrect = false,
                            Name = "1900",
                            QuestionsId = 7
                        },
                        new
                        {
                            Id = 28,
                            Iscorrect = false,
                            Name = "1917",
                            QuestionsId = 7
                        },
                        new
                        {
                            Id = 29,
                            Iscorrect = true,
                            Name = "Miguel de Cervantes",
                            QuestionsId = 8
                        },
                        new
                        {
                            Id = 30,
                            Iscorrect = false,
                            Name = "Gabriel garcia marquez",
                            QuestionsId = 8
                        },
                        new
                        {
                            Id = 31,
                            Iscorrect = false,
                            Name = "J. K. Rowling",
                            QuestionsId = 8
                        },
                        new
                        {
                            Id = 32,
                            Iscorrect = false,
                            Name = "Edgar Allan Poe",
                            QuestionsId = 8
                        },
                        new
                        {
                            Id = 33,
                            Iscorrect = false,
                            Name = "Vincent van Gogh",
                            QuestionsId = 9
                        },
                        new
                        {
                            Id = 34,
                            Iscorrect = false,
                            Name = "Frida Kahlo",
                            QuestionsId = 9
                        },
                        new
                        {
                            Id = 35,
                            Iscorrect = true,
                            Name = "Leonardo da Vinci",
                            QuestionsId = 9
                        },
                        new
                        {
                            Id = 36,
                            Iscorrect = false,
                            Name = "Fernando Botero",
                            QuestionsId = 9
                        },
                        new
                        {
                            Id = 37,
                            Iscorrect = false,
                            Name = "Carl Jung",
                            QuestionsId = 10
                        },
                        new
                        {
                            Id = 38,
                            Iscorrect = false,
                            Name = "Alfred Adler",
                            QuestionsId = 10
                        },
                        new
                        {
                            Id = 39,
                            Iscorrect = false,
                            Name = "Charcot",
                            QuestionsId = 10
                        },
                        new
                        {
                            Id = 40,
                            Iscorrect = true,
                            Name = "Sigmund Freud",
                            QuestionsId = 10
                        },
                        new
                        {
                            Id = 41,
                            Iscorrect = true,
                            Name = "Elvis Presley",
                            QuestionsId = 11
                        },
                        new
                        {
                            Id = 42,
                            Iscorrect = false,
                            Name = "Jimi hendrix",
                            QuestionsId = 11
                        },
                        new
                        {
                            Id = 43,
                            Iscorrect = false,
                            Name = "Carlos santana",
                            QuestionsId = 11
                        },
                        new
                        {
                            Id = 44,
                            Iscorrect = false,
                            Name = "Jerry Lee Lewis",
                            QuestionsId = 11
                        },
                        new
                        {
                            Id = 45,
                            Iscorrect = false,
                            Name = "Es la ciencia que estudia los mares",
                            QuestionsId = 12
                        },
                        new
                        {
                            Id = 46,
                            Iscorrect = true,
                            Name = "Es la ciencia que estudia los mapas",
                            QuestionsId = 12
                        },
                        new
                        {
                            Id = 47,
                            Iscorrect = false,
                            Name = "Es la ciencia que estudia los animales",
                            QuestionsId = 12
                        },
                        new
                        {
                            Id = 48,
                            Iscorrect = false,
                            Name = "Es la ciencia que estudia la tierra",
                            QuestionsId = 12
                        },
                        new
                        {
                            Id = 49,
                            Iscorrect = false,
                            Name = "China",
                            QuestionsId = 13
                        },
                        new
                        {
                            Id = 50,
                            Iscorrect = false,
                            Name = "Noruega",
                            QuestionsId = 13
                        },
                        new
                        {
                            Id = 51,
                            Iscorrect = false,
                            Name = "Italia",
                            QuestionsId = 13
                        },
                        new
                        {
                            Id = 52,
                            Iscorrect = true,
                            Name = "París",
                            QuestionsId = 13
                        },
                        new
                        {
                            Id = 53,
                            Iscorrect = true,
                            Name = "La Tierra",
                            QuestionsId = 14
                        },
                        new
                        {
                            Id = 54,
                            Iscorrect = false,
                            Name = "Venus",
                            QuestionsId = 14
                        },
                        new
                        {
                            Id = 55,
                            Iscorrect = false,
                            Name = "Jupiter",
                            QuestionsId = 14
                        },
                        new
                        {
                            Id = 56,
                            Iscorrect = false,
                            Name = "Mercurio",
                            QuestionsId = 14
                        },
                        new
                        {
                            Id = 57,
                            Iscorrect = false,
                            Name = "España",
                            QuestionsId = 15
                        },
                        new
                        {
                            Id = 58,
                            Iscorrect = false,
                            Name = "Francia",
                            QuestionsId = 15
                        },
                        new
                        {
                            Id = 59,
                            Iscorrect = false,
                            Name = "Ecuador",
                            QuestionsId = 15
                        },
                        new
                        {
                            Id = 60,
                            Iscorrect = true,
                            Name = "Italia",
                            QuestionsId = 15
                        },
                        new
                        {
                            Id = 61,
                            Iscorrect = false,
                            Name = "6 patas",
                            QuestionsId = 16
                        },
                        new
                        {
                            Id = 62,
                            Iscorrect = false,
                            Name = "10 patas",
                            QuestionsId = 16
                        },
                        new
                        {
                            Id = 63,
                            Iscorrect = true,
                            Name = "8 patas",
                            QuestionsId = 16
                        },
                        new
                        {
                            Id = 64,
                            Iscorrect = false,
                            Name = "4 patas",
                            QuestionsId = 16
                        },
                        new
                        {
                            Id = 65,
                            Iscorrect = false,
                            Name = "Tigre",
                            QuestionsId = 17
                        },
                        new
                        {
                            Id = 66,
                            Iscorrect = true,
                            Name = "Guepardo",
                            QuestionsId = 17
                        },
                        new
                        {
                            Id = 67,
                            Iscorrect = false,
                            Name = "Tortuga",
                            QuestionsId = 17
                        },
                        new
                        {
                            Id = 68,
                            Iscorrect = false,
                            Name = "Leon",
                            QuestionsId = 17
                        },
                        new
                        {
                            Id = 69,
                            Iscorrect = true,
                            Name = "Mir",
                            QuestionsId = 18
                        },
                        new
                        {
                            Id = 70,
                            Iscorrect = false,
                            Name = "NASA",
                            QuestionsId = 18
                        },
                        new
                        {
                            Id = 71,
                            Iscorrect = false,
                            Name = "FBI",
                            QuestionsId = 18
                        },
                        new
                        {
                            Id = 72,
                            Iscorrect = false,
                            Name = "CTI",
                            QuestionsId = 18
                        },
                        new
                        {
                            Id = 73,
                            Iscorrect = false,
                            Name = "El gato",
                            QuestionsId = 19
                        },
                        new
                        {
                            Id = 74,
                            Iscorrect = false,
                            Name = "El avestruz",
                            QuestionsId = 19
                        },
                        new
                        {
                            Id = 75,
                            Iscorrect = false,
                            Name = "Los Pingüinos",
                            QuestionsId = 19
                        },
                        new
                        {
                            Id = 76,
                            Iscorrect = true,
                            Name = "El murciélago",
                            QuestionsId = 19
                        },
                        new
                        {
                            Id = 77,
                            Iscorrect = true,
                            Name = "Chile",
                            QuestionsId = 20
                        },
                        new
                        {
                            Id = 78,
                            Iscorrect = false,
                            Name = "Argentina",
                            QuestionsId = 20
                        },
                        new
                        {
                            Id = 79,
                            Iscorrect = false,
                            Name = "Paraguay",
                            QuestionsId = 20
                        },
                        new
                        {
                            Id = 80,
                            Iscorrect = false,
                            Name = "Uruguay",
                            QuestionsId = 20
                        },
                        new
                        {
                            Id = 81,
                            Iscorrect = false,
                            Name = "Judas tadeo",
                            QuestionsId = 21
                        },
                        new
                        {
                            Id = 82,
                            Iscorrect = true,
                            Name = "Judas iscariote",
                            QuestionsId = 21
                        },
                        new
                        {
                            Id = 83,
                            Iscorrect = false,
                            Name = "San pedro",
                            QuestionsId = 21
                        },
                        new
                        {
                            Id = 84,
                            Iscorrect = false,
                            Name = "Francisco",
                            QuestionsId = 21
                        },
                        new
                        {
                            Id = 85,
                            Iscorrect = false,
                            Name = "Rusia",
                            QuestionsId = 22
                        },
                        new
                        {
                            Id = 86,
                            Iscorrect = false,
                            Name = "China",
                            QuestionsId = 22
                        },
                        new
                        {
                            Id = 87,
                            Iscorrect = true,
                            Name = "Japón",
                            QuestionsId = 22
                        },
                        new
                        {
                            Id = 88,
                            Iscorrect = false,
                            Name = "Ucrania",
                            QuestionsId = 22
                        },
                        new
                        {
                            Id = 89,
                            Iscorrect = false,
                            Name = "Azulejo",
                            QuestionsId = 23
                        },
                        new
                        {
                            Id = 90,
                            Iscorrect = false,
                            Name = "Maria mulata",
                            QuestionsId = 23
                        },
                        new
                        {
                            Id = 91,
                            Iscorrect = false,
                            Name = "Loros",
                            QuestionsId = 23
                        },
                        new
                        {
                            Id = 92,
                            Iscorrect = true,
                            Name = "Cuervo",
                            QuestionsId = 23
                        },
                        new
                        {
                            Id = 93,
                            Iscorrect = false,
                            Name = "1 corazones",
                            QuestionsId = 24
                        },
                        new
                        {
                            Id = 94,
                            Iscorrect = true,
                            Name = "3 corazones",
                            QuestionsId = 24
                        },
                        new
                        {
                            Id = 95,
                            Iscorrect = false,
                            Name = "4 corazones",
                            QuestionsId = 24
                        },
                        new
                        {
                            Id = 96,
                            Iscorrect = false,
                            Name = "2 corazones",
                            QuestionsId = 24
                        },
                        new
                        {
                            Id = 97,
                            Iscorrect = false,
                            Name = "Venezuela",
                            QuestionsId = 25
                        },
                        new
                        {
                            Id = 98,
                            Iscorrect = false,
                            Name = "Colombia",
                            QuestionsId = 25
                        },
                        new
                        {
                            Id = 99,
                            Iscorrect = true,
                            Name = "Etiopía",
                            QuestionsId = 25
                        },
                        new
                        {
                            Id = 100,
                            Iscorrect = false,
                            Name = "España",
                            QuestionsId = 25
                        });
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.Players", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("Idx_username_players");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriesId = 1,
                            Name = "¿Qué tipo de animal es la ballena?",
                            Score = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoriesId = 1,
                            Name = "¿Qué cantidad de huesos hay en el cuerpo humano?",
                            Score = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoriesId = 1,
                            Name = "¿Cuáles son los cinco tipos de sabores primarios?",
                            Score = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoriesId = 1,
                            Name = "¿Cuál es el lugar más frío de la tierra?",
                            Score = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoriesId = 1,
                            Name = "¿Cómo se llama la Reina del Reino Unido?",
                            Score = 2
                        },
                        new
                        {
                            Id = 6,
                            CategoriesId = 2,
                            Name = "¿Dónde originaron los juegos olímpicos?",
                            Score = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoriesId = 2,
                            Name = "¿Cuándo acabó la II Guerra Mundial?",
                            Score = 3
                        },
                        new
                        {
                            Id = 8,
                            CategoriesId = 2,
                            Name = "¿Quién es el autor de el Quijote?",
                            Score = 3
                        },
                        new
                        {
                            Id = 9,
                            CategoriesId = 2,
                            Name = "¿Quién pintó “la última cena”?",
                            Score = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoriesId = 2,
                            Name = "¿Quién es el padre del psicoanálisis?",
                            Score = 3
                        },
                        new
                        {
                            Id = 11,
                            CategoriesId = 3,
                            Name = "¿Quién es el famoso Rey de Rock en los Estados Unidos?",
                            Score = 4
                        },
                        new
                        {
                            Id = 12,
                            CategoriesId = 3,
                            Name = "¿Qué es la cartografía?",
                            Score = 4
                        },
                        new
                        {
                            Id = 13,
                            CategoriesId = 3,
                            Name = "¿Dónde se encuentra la famosa Torre Eiffel?",
                            Score = 4
                        },
                        new
                        {
                            Id = 14,
                            CategoriesId = 3,
                            Name = "¿Cuál es tercer planeta en el sistema solar?",
                            Score = 4
                        },
                        new
                        {
                            Id = 15,
                            CategoriesId = 3,
                            Name = "¿Qué país tiene forma de bota?",
                            Score = 4
                        },
                        new
                        {
                            Id = 16,
                            CategoriesId = 4,
                            Name = "¿Cuántas patas tiene la araña?",
                            Score = 5
                        },
                        new
                        {
                            Id = 17,
                            CategoriesId = 4,
                            Name = "¿Cómo se llama el animal más rápido del mundo?",
                            Score = 5
                        },
                        new
                        {
                            Id = 18,
                            CategoriesId = 4,
                            Name = "¿Cómo se llama la estación espacial rusa?",
                            Score = 5
                        },
                        new
                        {
                            Id = 19,
                            CategoriesId = 4,
                            Name = "¿Cuál es el único mamífero capaz de volar?",
                            Score = 5
                        },
                        new
                        {
                            Id = 20,
                            CategoriesId = 4,
                            Name = "¿Cuál es la nacionalidad de Pablo Neruda?",
                            Score = 5
                        },
                        new
                        {
                            Id = 21,
                            CategoriesId = 5,
                            Name = "¿Quién traicionó a Jesús?",
                            Score = 6
                        },
                        new
                        {
                            Id = 22,
                            CategoriesId = 5,
                            Name = "¿En qué país se usó la primera bomba atómica en combate?",
                            Score = 6
                        },
                        new
                        {
                            Id = 23,
                            CategoriesId = 5,
                            Name = "¿Cuál es el animal que tiene mayor facilidad para repetir las frases y palabras que escucha?",
                            Score = 6
                        },
                        new
                        {
                            Id = 24,
                            CategoriesId = 5,
                            Name = "¿Cuántos corazones tienen los pulpos?",
                            Score = 6
                        },
                        new
                        {
                            Id = 25,
                            CategoriesId = 5,
                            Name = "¿De qué país es originario el café?",
                            Score = 6
                        });
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.OptionsQuestions", b =>
                {
                    b.HasOne("SofkaUPrueba.Core.Entities.Questions", "Questions")
                        .WithMany("Options")
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.Questions", b =>
                {
                    b.HasOne("SofkaUPrueba.Core.Entities.Categories", "Categories")
                        .WithMany("Questions")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.Categories", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("SofkaUPrueba.Core.Entities.Questions", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
