const AUTH_INIT = "AUTH_INIT";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_ERROR = "AUTH_ERRORS";
const LOGOUT_INIT = "AUTH_INIT";
const LOGOUT_SUCCESS = "AUTH_SUCCESS";
const LOGOUT_ERROR = "AUTH_SUCCESS";

export {
    AUTH_INIT,
    AUTH_SUCCESS,
    AUTH_ERROR,
    LOGOUT_INIT,
    LOGOUT_SUCCESS,
    LOGOUT_ERROR
}