const FIND_WHERE_INIT = "FIND_WHERE_INIT";
const FIND_WHERE_SUCCESS = "FIND_WHERE_SUCCESS";
const FIND_WHERE_ERROR = "FIND_WHERE_ERROR";
const GAME_OVER = "GAME_OVER"
const NEXT_QUESTION = "NEXT_QUESTION"

export {
    FIND_WHERE_INIT,
    FIND_WHERE_SUCCESS,
    FIND_WHERE_ERROR,
    GAME_OVER,
    NEXT_QUESTION
}