const FIND_WHERE_INIT = "FIND_WHERE_INIT";
const FIND_WHERE_SUCCESS = "FIND_WHERE_SUCCESS";
const FIND_WHERE_ERROR = "FIND_WHERE_ERROR";

export {
    FIND_WHERE_INIT,
    FIND_WHERE_SUCCESS,
    FIND_WHERE_ERROR,
}